### Good request
POST http://localhost:8000/vm/start

{
    "cpu_count": 4,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}

### Stop (change ID)
POST http://localhost:8000/vm/38cf15e3eb5545a48db22dc34b15172f/stop

### CPU count too high
POST http://localhost:8000/vm/start

{
    "cpu_count": 400,
    "mem_size_gb": 32,
    "image": "debian:bookworm"
}